name: CI/CD

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build_FOR_UBUNTU:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # ... (rest of the Ubuntu build steps)

  build_FOR_MACOC:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: brew update && brew install boost glfw glm || { echo 'Failed to install dependencies'; exit 1; }
      - run: cmake . -DPATCH_VERSION=${github.run_number}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Check if tag exists for macOS
        id: check_tag_exists_macos
        run: |
          TAG="release-${github.run_number}-${github.sha}"
          if git tag -l | grep -q "$TAG"; then
            echo "tag_exists=true" >> $GITHUB_ENV;
          else
            echo "tag_exists=false" >> $GITHUB_ENV;
          fi
      - name: Create Release for macOS
        id: create_release_macos
        if: env.tag_exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-${github.run_number}-${github.sha}"
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset for macOS
        id: upload-release-asset-macos
        if: env.tag_exists == 'false'
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: helloworld-macOS.pkg
          path: ./helloworld-0.0.${github.run_number}-macOS.pkg
          retention_days: 30
      - name: Upload Source Code for macOS
        id: upload-source-code-macos
        if: env.tag_exists == 'false'
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-macOS-src
          path: ./src
          retention_days: 30
      - name: Upload Source Code Archive for macOS
        id: upload-source-code-archive-macos
        if: env.tag_exists == 'false'
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-macOS-src.zip
          path: ./src.zip
          retention_days: 30